exec_always --no-startup-id xss-lock --transfer-sleep-lock -- slock
exec_always --no-startup-id $HOME/.config/i3/scripts/launch.sh &
exec --no-startup-id $HOME/.config/i3/scripts/xinput.sh
exec --no-startup-id nm-applet
exec --no-startup-id blueman-applet
exec --no-startup-id exec $HOME/.fehbg
