# Font used
font pango:monospace 8

title_align center

popup_during_fullscreen smart

# Windows borders & gaps {{{
default_border pixel 1
hide_edge_borders smart_no_gaps

gaps inner 3
gaps outer 0
smart_gaps on
# }}}

# Colorscheme {{{
# class                 border  backgr. text indicator child_border
client.focused          $l_blue $l_blue $bg  $l_blue   $l_blue
client.unfocused        $d_blue $d_blue $fg  $d_blue   $d_blue
client.focused_inactive $l_blue $l_blue $bg  $l_blue   $l_blue
client.urgent           $d_red  $l_red  $fg  $l_red    $l_red
client.placeholder      $bg     $bg     $fg  $bg       $bg

client.background       $bg
# }}}
