;made by cheldux
;a mostly default polybar with gruvbox colorscheme

[colors]
bg = #282828
d_red = #cc241d
d_green = #98971a
d_yellow = #d79921
d_blue = #458588
d_purple = #b16286
d_aqua = #689d6a
l_grey = #a89984
d_grey = #928374
l_red = #fb4934
l_green = #b8bb26
l_yellow = #fabd2f
l_blue = #83a598
l_purple = #d3869b
l_aqua = #8ec07c
fg = #ebdbb2

bg0_h = #1d2021
bg0_s = #32302f
bg0 = #282828
bg1 = #3c3836
bg2 = #504945
bg3 = #665c54
bg4 = #7c6f64
grey = #928374
fg0 = #fbf1c7
fg1 = #ebdbb2
fg2 = #d5c4a1
fg3 = #bdae93
fg4 = #a89984
d_orange = #d65d0e
l_orange = #fe8019
transparent = #00000000

[settings]
screenchange-reload = true
pseudo-transparency = false

[bar/Desk]
monitor = ${env:MONITOR:}
width = 100%
height = 19
radius = 0
fixed-center = true
bottom=false

background = ${colors.bg0_h}
foreground = ${colors.fg}

line-size = 3
line-color = ${colors.fg}

border-size = 0
border-color = ${colors.fg}

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

separator = " "

font-0 = "IosevkaTerm Nerd Font Mono:fontformat=truetype:pixelsize=10:antialias=true;2"
font-1 = "IosevkaTerm Nerd Font Mono:fontformat=truetype:pixelsize=20:antialias=true;4"
font-2 = "IosevkaTerm Nerd Font Mono:fontformat=truetype:pixelsize=12:antialias=true;2"
font-3 = "IosevkaTerm Nerd Font Mono:fontformat=truetype:pixelsize=17:antialias=true;3"

modules-left = i3 filesystem xkeyboard
modules-center = date
modules-right = wlan eth memory cpu temperature pulseaudio backlight battery tray

cursor-click = pointer
cursor-scroll = ns-resize

[module/i3]
type = internal/i3
pin-workspace = false
enable-click = true
enable-scroll = true
wrapping-scroll = flase

label-focused = %index%
label-focused-foreground = ${colors.fg}
label-focused-background = ${colors.bg2}
label-focused-underline = ${colors.l_aqua}
label-focused-padding = 1

label-unfocused = %index%
label-unfocused-underline = ${colors.d_aqua}
label-unfocused-padding = 1

label-visible = %index%
label-visible-underline = ${colors.l_aqua}
label-visible-padding = 1

label-urgent = %index%
label-urgent-foreground = ${colors.fg}
label-urgent-background = ${colors.d_red}
label-urgent-underline = ${colors.l_red}
label-urgent-padding = 1

[module/filesystem]
type = internal/fs
mount-0 = /
fixed-values = true

format-mounted-underline = ${colors.l_blue}
format-mounted = %{T2}%{T-}:<label-mounted>

label-mounted = %mountpoint%%percentage_used%%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
blacklist-2 = caps lock

format = %{T2}%{T-}:<label-layout>
format-underline = ${colors.d_blue}

[module/date]
type = internal/date

format-underline = ${colors.d_purple}
format = %{T4}%{T-}:<label>

label = %date% %time%

date = %d/%m/%y
time = %H:%M

[module/wlan]
type = internal/network
interface = wlp3s0

format-connected-underline = ${colors.l_orange}
format-connected = %{T2}<ramp-signal>%{T-}:<label-connected>

format-disconnected-underline = ${colors.d_grey}
format-disconnected-foreground = ${colors.d_grey}
format-disconnected = %{T2}󰤭

label-connected = %{T2}%{T-}%downspeed% %{T2}%{T-}%upspeed%

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

[module/eth]
type = internal/network
interface = enp0s25

format-connected-underline = ${colors.d_orange}
format-connected = %{T2}󰈀%{T-}:<label-connected>

format-disconnected =

label-connected = %{T2}%{T-}%downspeed% %{T2}%{T-}%upspeed%

[module/memory]
type = internal/memory

format-underline = ${colors.l_yellow}
format = %{T2}%{T-}:<label>

format-warn-underline = ${colors.l_red}
format-warn-foreground = ${colors.l_red}
format-warn = %{T2}%{T-}:<label-warn>

[module/cpu]
type = internal/cpu

format-underline = ${colors.l_green}
format = %{T2}%{T-}:<label>

format-warn-underline = ${colors.l_red}
format-warn-foreground = ${colors.l_red}
format-warn = %{T2}%{T-}:<label-warn>

[module/temperature]
type = internal/temperature
thermal-zone = 0
base-temperature = 35

format-underline = ${colors.d_aqua}
format = %{T3}<ramp>%{T-}:<label>

format-warn-underline = ${colors.l_red}
format-warn-foreground = ${colors.l_red}
format-warn = %{T3}<ramp>%{T-}:<label-warn>

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
format-volume-underline = ${colors.l_blue}
format-volume = %{T2}󰕾%{T-}:<label-volume>
format-muted-underline = ${colors.d_grey}
format-muted-foreground = ${colors.d_grey}
format-muted = %{T2}󰖁

[module/backlight]
type = internal/backlight
enable-scroll = true

format-underline = ${colors.d_blue}
format = %{T2}%{T-}:<label>

[module/battery]
type = internal/battery

battery = BAT0
adapter = AC

format-charging-underline = ${colors.d_aqua}
format-charging = %{T3}<ramp-capacity>%{T-}:<label-charging>
format-discharging-underline = ${colors.d_yellow}
format-discharging = %{T3}<ramp-capacity>%{T-}:<label-discharging>
format-full-underline = ${colors.d_purple}
format-full = %{T3}<ramp-capacity>%{T-}:<label-full>

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁻
ramp-capacity-2 = 󰁼
ramp-capacity-3 = 󰁽
ramp-capacity-4 = 󰁾
ramp-capacity-5 = 󰁿
ramp-capacity-6 = 󰂀
ramp-capacity-7 = 󰂁
ramp-capacity-8 = 󰂂
ramp-capacity-9 = 󰁹

[module/tray]
type = internal/tray
tray-spacing = 0
tray-size = 100%
